version: '3.8'

services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/
    restart: always
