version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/certs  # Sertifika dosyalarını mount et
      - ./requirements/nginx/conf/:/etc/nginx/sites-available/
    restart: always
