version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/sites-enabled/abostano.42.fr.conf
    restart: always



