version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: on-failure
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wp-cli
    build: ./requirements/wordpress/
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html/
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb
    secrets:
      - db_password
      - db_root_password
      - credentials

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/sites-enabled/abostano.42.fr.conf
      - wp_data:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wp_data:

secrets:
  db_password:
    file: ./../secrets/db_password.txt
  db_root_password:
    file: ./../secrets/db_root_password.txt
  credentials:
    file: ./../secrets/credentials.txt